@HOST = http://localhost:4000/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiOSIsImV4cCI6MTcxNjI4MzkxNn0.5xtetH9OEJLj9lf15mxuzLeBQTRZjYkg_DHoktb692c

### 
# Register

POST {{HOST}}/auth/register
Content-Type: application/json

{
    "username":"test",
    "password":"Password",
    "name":"test"
}

### 
# Login

POST {{HOST}}/auth/login
Content-Type: application/json

{
    "username":"test",
    "password":"Password"
}

### 
# Auth User

GET  {{HOST}}/auth/user
Authorization: Bearer {{TOKEN}}

### 